### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by wqvbjhc** [yuanyuanxiang/RemoteController#1]
怎么使用，能否给个说明，谢谢！

**Comment by yuanyuanxiang** [comment]
1、将被控程序例如test.exe与守护程序（"Keeper/Keeper.exe"）放于同级目录，启动守护程序；
2、右键单击守护程序的托盘图标，进入“守护设置”，在“远程设备”填写RemoteController.exe所监听的IP与端口，点击确定；
3、启动RemoteController.exe，通过菜单进入“本地监听”，设置其所监听的IP与端口，点击确定；
4、此时，Keeper将和RemoteController建立连接，通过RemoteController即可对test.exe进行监控。
